"""The generic fallback pack: a runnable, tested skeleton for any direction.

This is where determinism is honest about its boundary: for an unrecognized
domain, detcode cannot invent the logic — so it generates the structure,
records its decisions, and marks exactly where the domain logic goes, with
pointers to the example-driven tools that can grow it.
"""
from __future__ import annotations

from . import Pack

_CORE = '''
"""Core logic for __PKG__.

detcode generated this skeleton deterministically. The domain logic is yours
to specify — add functions here directly, or grow them example-first:

    detcode do "write a function score where score([1, 2]) == 3"
    detcode gentest --spec examples.json --file __PKG__/core.py
"""


def run(args):
    """Entry point for the __PKG__ pipeline."""
    raise NotImplementedError(
        "the domain logic for this project is not derivable from the "
        "direction alone; see __PKG__/core.py for how to grow it"
    )
'''

_CLI = '''
"""Command-line interface for __PKG__."""
import argparse

from . import core


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="__PKG__")
    parser.add_argument("inputs", nargs="*", help="input files")
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    core.run(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

_MAIN = '''
"""Enables python -m __PKG__."""
from .cli import main

if __name__ == "__main__":
    raise SystemExit(main())
'''

_TESTS = '''
"""Tests for the generated __PKG__ skeleton."""
import unittest

from __PKG__ import core
from __PKG__.cli import build_parser


class SkeletonTests(unittest.TestCase):
    def test_cli_parser_builds(self):
        args = build_parser().parse_args(["a.txt"])
        self.assertEqual(args.inputs, ["a.txt"])

    def test_core_is_explicit_about_missing_logic(self):
        # The skeleton must fail loudly, never pretend to work.
        with self.assertRaises(NotImplementedError):
            core.run(None)


if __name__ == "__main__":
    unittest.main()
'''


def _files() -> dict[str, str]:
    return {
        "__PKG__/__init__.py": '"""__PKG__ (generated by detcode)."""\n',
        "__PKG__/core.py": _CORE.lstrip("\n"),
        "__PKG__/cli.py": _CLI.lstrip("\n"),
        "__PKG__/__main__.py": _MAIN.lstrip("\n"),
        "tests/__init__.py": "",
        "tests/test___PKG__.py": _TESTS.lstrip("\n"),
    }


PACK = Pack(
    key="generic",
    title="Project skeleton",
    default_slug="",
    keywords=frozenset(),
    description=(
        "a runnable package skeleton with CLI and tests; the domain logic is "
        "marked for you to specify"
    ),
    files=_files,
)
