"""The --web wrapper: a stdlib WSGI UI over any generated project's CLI.

Every pack (generic included) exposes ``cli.main(argv) -> int`` that prints to
stdout — so one uniform wrapper serves them all: commands typed in the browser
run the CLI in-process with stdout/stderr captured, exactly the pattern
detcode's own playground uses. No dependencies, no pack-specific code.
"""
from __future__ import annotations

_WEB = '''
"""Minimal web UI for __PKG__ (generated by detcode --web).

Wraps the package CLI in a stdlib WSGI app: a command typed in the browser
runs ``cli.main(argv)`` with stdout/stderr captured and returned.

    python devserver.py    ->  http://127.0.0.1:8000
"""
import io
import json
import shlex
from contextlib import redirect_stderr, redirect_stdout

from .cli import main as cli_main

PAGE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>__PKG__</title>
<style>
  body { background: #181818; color: #ccc; font-family: ui-monospace, Consolas, monospace;
         max-width: 860px; margin: 40px auto; padding: 0 20px; font-size: 14px; }
  h1 { color: #fff; font-weight: 400; font-size: 20px; }
  .row { display: flex; gap: 8px; margin: 16px 0; }
  .tp { color: #89d185; align-self: center; }
  input { flex: 1; background: #252526; color: #ccc; border: 1px solid #3c3c3c;
          border-radius: 3px; padding: 8px 10px; font: inherit; }
  pre { background: #1e1e1e; border: 1px solid #3c3c3c; border-radius: 3px;
        padding: 12px; white-space: pre-wrap; min-height: 60px; }
  pre.err { color: #f48771; }
  .dim { color: #8a8a8a; font-size: 12.5px; }
</style></head><body>
<h1>__PKG__</h1>
<p class="dim">Commands run the package CLI (deterministic). Try: <code>--help</code></p>
<div class="row"><span class="tp">__PKG__&gt;</span>
<input id="cmd" autofocus placeholder="--help"></div>
<pre id="out"></pre>
<script>
const input = document.getElementById("cmd"), out = document.getElementById("out");
input.addEventListener("keydown", async e => {
  if (e.key !== "Enter") return;
  const res = await fetch("/api/run", { method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ command: input.value }) });
  const data = await res.json();
  out.textContent = data.output || "(no output)";
  out.className = data.ok ? "" : "err";
});
</script></body></html>
"""


def run_command(command):
    """Run one CLI invocation in-process, capturing all output."""
    try:
        argv = shlex.split(command)
    except ValueError as exc:
        return {"ok": False, "exit": 2, "output": f"could not parse command: {exc}"}
    buffer = io.StringIO()
    code = 0
    try:
        with redirect_stdout(buffer), redirect_stderr(buffer):
            code = cli_main(argv) or 0
    except SystemExit as exc:
        code = exc.code if isinstance(exc.code, int) else (0 if exc.code is None else 1)
    except Exception as exc:
        buffer.write(f"error: {exc}")
        code = 1
    return {"ok": code == 0, "exit": code, "output": buffer.getvalue()}


def app(environ, start_response):
    method = environ.get("REQUEST_METHOD", "GET")
    head = method == "HEAD"
    path = (environ.get("PATH_INFO") or "/").rstrip("/") or "/"

    def respond(status, content_type, body):
        start_response(status, [("Content-Type", content_type),
                                ("Content-Length", str(len(body)))])
        return [] if head else [body]

    if path == "/api/run" and method == "POST":
        try:
            length = int(environ.get("CONTENT_LENGTH") or 0)
            request = json.loads(environ["wsgi.input"].read(length) or b"{}")
            result = run_command(str(request.get("command") or ""))
        except (ValueError, json.JSONDecodeError):
            result = {"ok": False, "exit": 2, "output": "body must be valid JSON"}
        return respond("200 OK", "application/json; charset=utf-8",
                       json.dumps(result).encode("utf-8"))
    if path == "/" and method in ("GET", "HEAD"):
        return respond("200 OK", "text/html; charset=utf-8", PAGE.encode("utf-8"))
    return respond("404 Not Found", "application/json; charset=utf-8",
                   b'{"ok": false, "output": "not found"}')
'''

_DEVSERVER = '''
"""Run the __PKG__ web UI locally: python devserver.py [port]"""
import sys
from socketserver import ThreadingMixIn
from wsgiref.simple_server import WSGIServer, make_server

from __PKG__.web import app


class ThreadingWSGIServer(ThreadingMixIn, WSGIServer):
    daemon_threads = True


def main() -> None:
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    with make_server("127.0.0.1", port, app, server_class=ThreadingWSGIServer) as server:
        print(f"__PKG__ web ui: http://127.0.0.1:{port}")
        server.serve_forever()


if __name__ == "__main__":
    main()
'''


def files() -> dict[str, str]:
    return {
        "__PKG__/web.py": _WEB.lstrip("\n"),
        "devserver.py": _DEVSERVER.lstrip("\n"),
    }
