"""Deterministic test generation.

Given a function name and input/output examples, emit a runnable ``unittest``
module — one test method per example. LLMs write tests constantly; the
example-to-assertion translation is purely mechanical, so it can be done
deterministically and byte-reproducibly.

Two source modes:
- ``spec["source"]``: the code under test is embedded in the generated file
  (self-contained — pairs naturally with ``synth`` output).
- ``spec["module"]``: the generated file imports the function instead.

Generating tests that *fail* is valid (that is TDD); the generator only
guarantees the file is syntactically valid and faithful to the examples.
"""
from __future__ import annotations

import ast
from dataclasses import dataclass

from ..determinism import provenance

RULE_VERSION = "1"
INDENT = "    "


class SpecError(Exception):
    """The gentest spec was malformed."""


@dataclass
class Result:
    source: str
    report: dict


def _camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)


def _validate(spec: dict) -> tuple[str, list[dict]]:
    if not isinstance(spec, dict):
        raise SpecError("spec must be a JSON object")
    func = spec.get("function")
    if not isinstance(func, str) or not func.isidentifier():
        raise SpecError("spec must name a valid 'function'")
    examples = spec.get("examples")
    if not isinstance(examples, list) or not examples:
        raise SpecError("spec must provide a non-empty 'examples' list")
    for i, ex in enumerate(examples):
        if not isinstance(ex, dict) or "in" not in ex or "out" not in ex:
            raise SpecError(f"example {i} must have 'in' and 'out'")
        if not isinstance(ex["in"], list):
            raise SpecError(f"example {i} 'in' must be a list")
    return func, examples


def gentest(spec: dict) -> Result:
    func, examples = _validate(spec)

    source = spec.get("source")
    module = spec.get("module")
    if source is not None:
        try:
            ast.parse(source)
        except SyntaxError as exc:
            raise SpecError(f"'source' is not valid Python: {exc}") from exc
        header = source.rstrip("\n")
        mode = "inline-source"
    elif module is not None:
        if not all(part.isidentifier() for part in str(module).split(".")):
            raise SpecError(f"'module' {module!r} is not a valid module path")
        header = f"from {module} import {func}"
        mode = "import"
    else:
        raise SpecError("spec needs 'source' (code under test) or 'module' (import path)")

    lines = [
        f'"""Tests for {func} (generated by detcode gentest)."""',
        "import unittest",
        "",
        "",
        header,
        "",
        "",
        f"class Test{_camel(func)}(unittest.TestCase):",
    ]
    for i, ex in enumerate(examples):
        args = ", ".join(repr(a) for a in ex["in"])
        lines.append(f"{INDENT}def test_{func}_{i}(self):")
        lines.append(f"{INDENT}{INDENT}self.assertEqual({func}({args}), {ex['out']!r})")
        lines.append("")
    lines.extend(
        [
            "",
            'if __name__ == "__main__":',
            f"{INDENT}unittest.main()",
        ]
    )
    generated = "\n".join(lines) + "\n"
    ast.parse(generated)  # generated file must be valid Python

    report = provenance(
        "gentest", RULE_VERSION, function=func, cases=len(examples), mode=mode
    )
    return Result(generated, report)
