"""Django stack: a Django project over the generated package's CLI.

Real Django layout — ``manage.py`` plus a ``config`` project package — with
the same uniform pattern as every other web stack: commands typed in the
browser run ``cli.main(argv)`` in-process with output captured. The domain
packs' core rides along untouched.
"""
from __future__ import annotations

from . import Stack
from ._shared import PAGE_AND_RUNNER

_MANAGE = '''#!/usr/bin/env python
"""Django management entry point for __PKG__ (generated by detcode)."""
import os
import sys


def main() -> None:
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
'''

_SETTINGS = '''"""Django settings for the __PKG__ project (generated by detcode, stack: django).

Deliberately minimal: no database, no auth, no sessions — the project wraps a
deterministic CLI. Add Django apps as the project grows.
"""
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Generated placeholder — rotate before deploying anywhere real.
SECRET_KEY = "django-insecure-__PKG__-change-me-before-deploying"
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "0.0.0.0"]

INSTALLED_APPS = []
MIDDLEWARE = ["django.middleware.common.CommonMiddleware"]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

TEMPLATES = []
DATABASES = {}

USE_TZ = True
'''

_URLS = '''"""URL routes for __PKG__ (generated by detcode, stack: django)."""
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index),
    path("api/run", views.api_run),
]
'''

_VIEWS = (
    '''"""Views wrapping the __PKG__ CLI (generated by detcode, stack: django).

A command posted from the browser runs ``cli.main(argv)`` in-process with
stdout/stderr captured and returned — the same uniform pattern every detcode
web stack uses.
"""
import io
import json
import shlex
from contextlib import redirect_stderr, redirect_stdout

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from __PKG__.cli import main as cli_main

'''
    + PAGE_AND_RUNNER
    + '''

def index(request):
    return HttpResponse(PAGE)


@csrf_exempt
def api_run(request):
    if request.method != "POST":
        return JsonResponse({"ok": False, "output": "POST a JSON body"}, status=405)
    try:
        payload = json.loads(request.body or b"{}")
    except json.JSONDecodeError:
        return JsonResponse({"ok": False, "output": "body must be valid JSON"}, status=400)
    return JsonResponse(run_command(str(payload.get("command") or "")))
'''
)

_WSGI = '''"""WSGI entry point for __PKG__ (generated by detcode, stack: django)."""
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
application = get_wsgi_application()
'''

_ASGI = '''"""ASGI entry point for __PKG__ (generated by detcode, stack: django)."""
import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
application = get_asgi_application()
'''


def _files() -> dict[str, str]:
    return {
        "manage.py": _MANAGE,
        "config/__init__.py": '"""Django project package for __PKG__ (generated by detcode)."""\n',
        "config/settings.py": _SETTINGS,
        "config/urls.py": _URLS,
        "config/views.py": _VIEWS,
        "config/wsgi.py": _WSGI,
        "config/asgi.py": _ASGI,
    }


STACK = Stack(
    key="django",
    title="Django",
    keywords=frozenset({"django"}),
    description="a Django project over the generated core; adds dependency: django",
    language="python",
    dependencies=("django",),
    web_files=_files,
    web_always=True,
    web_label="a Django app",
    web_run="python manage.py runserver",
    usage=(
        "pip install -e .              # pulls in django",
        "python -m __PKG__ --help",
        "python manage.py runserver    # web UI at http://127.0.0.1:8000",
    ),
    dev=("python -m unittest discover -s tests",),
    docker=(
        "FROM python:3.12-slim\n"
        "WORKDIR /app\n"
        "COPY . .\n"
        "RUN pip install --no-cache-dir -e .\n"
        "EXPOSE 8000\n"
        'CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]\n'
    ),
)
