"""Express stack: an Express (ES modules) app over the project's CLI.

Same uniform pattern as every detcode web stack — commands run ``main(argv)``
in-process with the result returned as JSON — served by Express, with the
dependency recorded in package.json. Tests do a real HTTP round trip against
``app.listen(0)`` using Node's built-in test runner and fetch.
"""
from __future__ import annotations

from . import Stack

_PACKAGE_JSON = '''{
  "name": "__PKG__",
  "version": "0.1.0",
  "description": "__PKG__ (generated by detcode)",
  "type": "module",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "test": "node --test"
  },
  "dependencies": {
    "express": "^4.19.2"
  },
  "engines": { "node": ">=20" }
}
'''

_CORE = '''/**
 * Core logic for __PKG__.
 *
 * detcode generated this skeleton deterministically. The domain logic is
 * yours to specify: detcode's domain packs are Python-only, so on the Express
 * stack this function fails loudly instead of pretending to work.
 */
export function run(args) {
  throw new Error(
    "the domain logic for this project is not derivable from the direction alone; implement it in src/core.js"
  );
}
'''

_CLI = '''/** Command-line interface for __PKG__: node src/cli.js [inputs...] */
import { pathToFileURL } from "node:url";

import { run } from "./core.js";

const USAGE = [
  "__PKG__ - generated by detcode (stack: express)",
  "",
  "usage:",
  "  node src/cli.js [inputs...]    run the core pipeline",
  "  node server.js [port]          Express web UI at http://127.0.0.1:8000",
  "  npm install && node --test     run the test suite",
  "",
  "The domain logic lives in src/core.js - a skeleton that fails loudly",
  "until you implement it.",
].join("\\n");

export function main(argv) {
  if (argv.length === 0 || argv.includes("--help") || argv.includes("-h")) {
    return { code: 0, output: USAGE };
  }
  try {
    return { code: 0, output: String(run(argv)) };
  } catch (err) {
    return { code: 1, output: `error: ${err.message}` };
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { code, output } = main(process.argv.slice(2));
  console.log(output);
  process.exit(code);
}
'''

_SERVER = '''/**
 * Express web UI for __PKG__ (generated by detcode, stack: express).
 *
 * Wraps the CLI in an Express app: a command typed in the browser runs
 * `main(argv)` in-process and returns its output.
 *
 *     npm install
 *     node server.js [port]    ->  http://127.0.0.1:8000
 */
import { pathToFileURL } from "node:url";

import express from "express";

import { main } from "./src/cli.js";

export const app = express();
app.use(express.json());

const PAGE = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>__PKG__</title>
<style>
  body { background: #181818; color: #ccc; font-family: ui-monospace, Consolas, monospace;
         max-width: 860px; margin: 40px auto; padding: 0 20px; font-size: 14px; }
  h1 { color: #fff; font-weight: 400; font-size: 20px; }
  .row { display: flex; gap: 8px; margin: 16px 0; }
  .tp { color: #89d185; align-self: center; }
  input { flex: 1; background: #252526; color: #ccc; border: 1px solid #3c3c3c;
          border-radius: 3px; padding: 8px 10px; font: inherit; }
  pre { background: #1e1e1e; border: 1px solid #3c3c3c; border-radius: 3px;
        padding: 12px; white-space: pre-wrap; min-height: 60px; }
  pre.err { color: #f48771; }
  .dim { color: #8a8a8a; font-size: 12.5px; }
</style></head><body>
<h1>__PKG__</h1>
<p class="dim">Commands run the project CLI (deterministic). Try: <code>--help</code></p>
<div class="row"><span class="tp">__PKG__&gt;</span>
<input id="cmd" autofocus placeholder="--help"></div>
<pre id="out"></pre>
<script>
const input = document.getElementById("cmd"), out = document.getElementById("out");
input.addEventListener("keydown", async e => {
  if (e.key !== "Enter") return;
  const res = await fetch("/api/run", { method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ command: input.value }) });
  const data = await res.json();
  out.textContent = data.output || "(no output)";
  out.className = data.ok ? "" : "err";
});
</script></body></html>
`;

app.get("/", (req, res) => res.type("html").send(PAGE));

app.post("/api/run", (req, res) => {
  const command = String((req.body && req.body.command) || "");
  const { code, output } = main(command.split(/\\s+/).filter(Boolean));
  res.json({ ok: code === 0, exit: code, output });
});

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const port = Number(process.argv[2]) || 8000;
  const host = process.env.HOST || "127.0.0.1";
  app.listen(port, host, () =>
    console.log(`__PKG__ web ui: http://${host}:${port}`)
  );
}
'''

_CORE_TESTS = '''/** Tests for the generated __PKG__ skeleton: node --test */
import test from "node:test";
import assert from "node:assert/strict";

import { main } from "../src/cli.js";
import { run } from "../src/core.js";

test("cli --help is ok", () => {
  const { code, output } = main(["--help"]);
  assert.equal(code, 0);
  assert.match(output, /usage/);
});

test("core is explicit about missing logic", () => {
  // The skeleton must fail loudly, never pretend to work.
  assert.throws(() => run([]), /not derivable/);
});
'''

_SERVER_TESTS = '''/** HTTP round-trip tests for the Express app: npm install && node --test */
import test from "node:test";
import assert from "node:assert/strict";

import { app } from "../server.js";

function listen() {
  return new Promise((resolve) => {
    const server = app.listen(0, "127.0.0.1", () => resolve(server));
  });
}

test("GET / serves the page", async () => {
  const server = await listen();
  try {
    const res = await fetch(`http://127.0.0.1:${server.address().port}/`);
    assert.equal(res.status, 200);
    assert.match(await res.text(), /__PKG__/);
  } finally {
    server.close();
  }
});

test("POST /api/run runs the cli", async () => {
  const server = await listen();
  try {
    const res = await fetch(`http://127.0.0.1:${server.address().port}/api/run`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ command: "--help" }),
    });
    const data = await res.json();
    assert.equal(data.ok, true);
    assert.match(data.output, /usage/);
  } finally {
    server.close();
  }
});
'''


def _files() -> dict[str, str]:
    return {
        "package.json": _PACKAGE_JSON,
        "src/core.js": _CORE,
        "src/cli.js": _CLI,
        "server.js": _SERVER,
        "tests/core.test.js": _CORE_TESTS,
        "tests/server.test.js": _SERVER_TESTS,
    }


STACK = Stack(
    key="express",
    title="Express",
    keywords=frozenset({"express", "expressjs"}),
    description=(
        "an Express (ES modules) web app with CLI and node --test suite; "
        "adds dependency: express"
    ),
    language="javascript",
    skeleton=_files,
    web_always=True,
    web_label="an Express web app",
    usage=(
        "npm install",
        "node src/cli.js --help",
        "node server.js         # web UI at http://127.0.0.1:8000",
    ),
    dev=("npm install", "node --test"),
    interface_line=(
        "interface: Express web app (node server.js) plus command-line "
        "(node src/cli.js)"
    ),
    gitignore="node_modules/\n*.log\n",
    ci=(
        "name: ci\n\non:\n  push:\n  pull_request:\n\njobs:\n  test:\n"
        "    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-node@v4\n"
        '        with: { node-version: "22" }\n'
        "      - name: Install\n"
        "        run: npm install\n"
        "      - name: Tests\n"
        "        run: node --test\n"
    ),
    docker=(
        "FROM node:22-slim\n"
        "WORKDIR /app\n"
        "COPY . .\n"
        "RUN npm install --omit=dev\n"
        "ENV HOST=0.0.0.0\n"
        "EXPOSE 8000\n"
        'CMD ["node", "server.js"]\n'
    ),
)
