"""FastAPI stack: a FastAPI app (served by uvicorn) over the package's CLI.

Same uniform pattern as the stdlib webwrap — commands run ``cli.main(argv)``
in-process with output captured — but served by FastAPI/uvicorn, with the
dependencies recorded in the generated pyproject.
"""
from __future__ import annotations

from . import Stack
from ._shared import PAGE_AND_RUNNER

_WEB = (
    '''"""FastAPI web UI for __PKG__ (generated by detcode, stack: fastapi).

Wraps the package CLI in a FastAPI app: a command typed in the browser runs
``cli.main(argv)`` with stdout/stderr captured and returned.

    pip install -e .       # installs fastapi + uvicorn (see pyproject.toml)
    python devserver.py    ->  http://127.0.0.1:8000
"""
import io
import shlex
from contextlib import redirect_stderr, redirect_stdout

from fastapi import FastAPI
from fastapi.responses import HTMLResponse

from .cli import main as cli_main

app = FastAPI(title="__PKG__")

'''
    + PAGE_AND_RUNNER
    + '''

@app.get("/", response_class=HTMLResponse)
def index():
    return PAGE


@app.post("/api/run")
def api_run(payload: dict):
    return run_command(str(payload.get("command") or ""))
'''
)

_DEVSERVER = '''"""Run the __PKG__ FastAPI app locally: python devserver.py [port]"""
import sys

import uvicorn

from __PKG__.web import app


def main() -> None:
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    uvicorn.run(app, host="127.0.0.1", port=port)


if __name__ == "__main__":
    main()
'''


def _files() -> dict[str, str]:
    return {"__PKG__/web.py": _WEB, "devserver.py": _DEVSERVER}


STACK = Stack(
    key="fastapi",
    title="FastAPI",
    keywords=frozenset({"fastapi", "uvicorn"}),
    description="a FastAPI app served by uvicorn; adds dependencies: fastapi, uvicorn",
    language="python",
    dependencies=("fastapi", "uvicorn"),
    web_files=_files,
    skeleton=None,
    web_always=True,
    web_label="a FastAPI app (uvicorn)",
    usage=(
        "pip install -e .       # pulls in fastapi + uvicorn",
        "python -m __PKG__ --help",
        "python devserver.py    # web UI at http://127.0.0.1:8000",
    ),
    dev=("python -m unittest discover -s tests",),
)
