"""Flask stack: a Flask app over the generated package's CLI.

Same uniform pattern as the stdlib webwrap — commands run ``cli.main(argv)``
in-process with output captured — but served by Flask, and the dependency
lands in the generated pyproject.
"""
from __future__ import annotations

from . import Stack
from ._shared import PAGE_AND_RUNNER

_WEB = (
    '''"""Flask web UI for __PKG__ (generated by detcode, stack: flask).

Wraps the package CLI in a Flask app: a command typed in the browser runs
``cli.main(argv)`` with stdout/stderr captured and returned.

    pip install -e .       # installs flask (see pyproject.toml)
    python devserver.py    ->  http://127.0.0.1:8000
"""
import io
import shlex
from contextlib import redirect_stderr, redirect_stdout

from flask import Flask, jsonify, request

from .cli import main as cli_main

app = Flask(__name__)

'''
    + PAGE_AND_RUNNER
    + '''

@app.get("/")
def index():
    return PAGE


@app.post("/api/run")
def api_run():
    payload = request.get_json(silent=True) or {}
    return jsonify(run_command(str(payload.get("command") or "")))
'''
)

_DEVSERVER = '''"""Run the __PKG__ Flask app locally: python devserver.py [port]"""
import sys

from __PKG__.web import app


def main() -> None:
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    app.run(host="127.0.0.1", port=port)


if __name__ == "__main__":
    main()
'''


def _files() -> dict[str, str]:
    return {"__PKG__/web.py": _WEB, "devserver.py": _DEVSERVER}


STACK = Stack(
    key="flask",
    title="Flask",
    keywords=frozenset({"flask"}),
    description="a Flask web app over the generated core; adds dependency: flask",
    language="python",
    dependencies=("flask",),
    web_files=_files,
    skeleton=None,
    web_always=True,
    web_label="a Flask web app",
    usage=(
        "pip install -e .       # pulls in flask",
        "python -m __PKG__ --help",
        "python devserver.py    # web UI at http://127.0.0.1:8000",
    ),
    dev=("python -m unittest discover -s tests",),
    docker=(
        "FROM python:3.12-slim\n"
        "WORKDIR /app\n"
        "COPY . .\n"
        "RUN pip install --no-cache-dir -e .\n"
        "EXPOSE 8000\n"
        'CMD ["flask", "--app", "__PKG__.web", "run", "--host=0.0.0.0", "--port=8000"]\n'
    ),
)
