"""Go stack: a std-only Go module — net/http web UI, CLI, and go test suite.

The same "stdlib first" idiom as detcode's own Python projects: no third-party
imports, one module, table-driven tests. The web UI follows the uniform
detcode pattern (commands run the core in-process, output returned as JSON).
"""
from __future__ import annotations

from . import Stack


def _tabs(source: str) -> str:
    """Convert 4-space indentation to tabs (gofmt style).

    The templates stay space-indented in this file so detcode's own advise
    gate (no tabs in .py sources) holds; generated Go files get real tabs.
    """
    out = []
    for line in source.split("\n"):
        stripped = line.lstrip(" ")
        indent = (len(line) - len(stripped)) // 4
        out.append("\t" * indent + stripped)
    return "\n".join(out)


_GO_MOD = '''module __PKG__

go 1.22
'''

_MAIN = '''// Command __PKG__: CLI plus a dependency-free net/http web UI (generated by detcode).
package main

import (
    "encoding/json"
    "fmt"
    "net/http"
    "os"
    "strings"

    "__PKG__/core"
)

const usage = `__PKG__ - generated by detcode (stack: go)

usage:
    go run . [inputs...]     run the core pipeline
    go run . serve [port]    web UI at http://127.0.0.1:8000
    go test ./...            run the test suite

The domain logic lives in core/core.go - a skeleton that fails loudly
until you implement it.`

func wantsHelp(args []string) bool {
    if len(args) == 0 {
        return true
    }
    for _, arg := range args {
        if arg == "--help" || arg == "-h" || arg == "help" {
            return true
        }
    }
    return false
}

func runCommand(command string) map[string]any {
    fields := strings.Fields(command)
    if wantsHelp(fields) {
        return map[string]any{"ok": true, "exit": 0, "output": usage}
    }
    output, err := core.Run(fields)
    if err != nil {
        return map[string]any{"ok": false, "exit": 1, "output": "error: " + err.Error()}
    }
    return map[string]any{"ok": true, "exit": 0, "output": output}
}

func serve(args []string) {
    port := "8000"
    if len(args) > 0 {
        port = args[0]
    }
    host := os.Getenv("HOST")
    if host == "" {
        host = "127.0.0.1"
    }
    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        if r.URL.Path != "/" {
            http.NotFound(w, r)
            return
        }
        w.Header().Set("Content-Type", "text/html; charset=utf-8")
        fmt.Fprint(w, page)
    })
    http.HandleFunc("/api/run", func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Type", "application/json")
        if r.Method != http.MethodPost {
            w.WriteHeader(http.StatusMethodNotAllowed)
            json.NewEncoder(w).Encode(map[string]any{"ok": false, "output": "POST a JSON body"})
            return
        }
        var body map[string]string
        if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
            w.WriteHeader(http.StatusBadRequest)
            json.NewEncoder(w).Encode(map[string]any{"ok": false, "output": "body must be valid JSON"})
            return
        }
        json.NewEncoder(w).Encode(runCommand(body["command"]))
    })
    addr := host + ":" + port
    fmt.Printf("__PKG__ web ui: http://%s\\n", addr)
    if err := http.ListenAndServe(addr, nil); err != nil {
        fmt.Fprintln(os.Stderr, err)
        os.Exit(1)
    }
}

func main() {
    args := os.Args[1:]
    if len(args) > 0 && args[0] == "serve" {
        serve(args[1:])
        return
    }
    if wantsHelp(args) {
        fmt.Println(usage)
        return
    }
    output, err := core.Run(args)
    if err != nil {
        fmt.Fprintln(os.Stderr, "error: "+err.Error())
        os.Exit(1)
    }
    fmt.Println(output)
}
'''

# The page lives in its own file; Go raw strings cannot contain backticks, so
# the embedded JS sticks to plain quotes (no template literals). The CSS keeps
# its 2-space indentation, so this template skips the tab conversion.
_PAGE = '''package main

const page = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>__PKG__</title>
<style>
  body { background: #181818; color: #ccc; font-family: ui-monospace, Consolas, monospace;
         max-width: 860px; margin: 40px auto; padding: 0 20px; font-size: 14px; }
  h1 { color: #fff; font-weight: 400; font-size: 20px; }
  .row { display: flex; gap: 8px; margin: 16px 0; }
  .tp { color: #89d185; align-self: center; }
  input { flex: 1; background: #252526; color: #ccc; border: 1px solid #3c3c3c;
          border-radius: 3px; padding: 8px 10px; font: inherit; }
  pre { background: #1e1e1e; border: 1px solid #3c3c3c; border-radius: 3px;
        padding: 12px; white-space: pre-wrap; min-height: 60px; }
  pre.err { color: #f48771; }
  .dim { color: #8a8a8a; font-size: 12.5px; }
</style></head><body>
<h1>__PKG__</h1>
<p class="dim">Commands run the project CLI (deterministic). Try: <code>--help</code></p>
<div class="row"><span class="tp">__PKG__&gt;</span>
<input id="cmd" autofocus placeholder="--help"></div>
<pre id="out"></pre>
<script>
const input = document.getElementById("cmd"), out = document.getElementById("out");
input.addEventListener("keydown", async e => {
  if (e.key !== "Enter") return;
  const res = await fetch("/api/run", { method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ command: input.value }) });
  const data = await res.json();
  out.textContent = data.output || "(no output)";
  out.className = data.ok ? "" : "err";
});
</script></body></html>
`
'''

_CORE = '''// Package core holds the domain logic for __PKG__.
//
// detcode generated this skeleton deterministically. The domain logic is
// yours to specify: detcode's domain packs are Python-only, so on the Go
// stack this function fails loudly instead of pretending to work.
package core

import "errors"

// Run is the entry point for the __PKG__ pipeline.
func Run(args []string) (string, error) {
    return "", errors.New(
        "the domain logic for this project is not derivable from the direction alone; implement it in core/core.go",
    )
}
'''

_CORE_TEST = '''package core

import (
    "strings"
    "testing"
)

// The skeleton must fail loudly, never pretend to work.
func TestRunIsExplicitAboutMissingLogic(t *testing.T) {
    _, err := Run([]string{"input.txt"})
    if err == nil {
        t.Fatal("expected the skeleton to fail loudly, got nil error")
    }
    if !strings.Contains(err.Error(), "not derivable") {
        t.Fatalf("unexpected error: %v", err)
    }
}
'''


def _files() -> dict[str, str]:
    return {
        "go.mod": _GO_MOD,
        "main.go": _tabs(_MAIN),
        "page.go": _PAGE,
        "core/core.go": _tabs(_CORE),
        "core/core_test.go": _tabs(_CORE_TEST),
    }


STACK = Stack(
    key="go",
    title="Go",
    keywords=frozenset({"golang"}),
    description=(
        "a std-only Go module — net/http web UI, CLI, and go test suite "
        '(say "golang" or use --stack go; bare "go" is too ambiguous to match)'
    ),
    language="go",
    skeleton=_files,
    web_always=True,
    web_label="a net/http web UI",
    usage=(
        "go run . --help",
        "go run . serve           # web UI at http://127.0.0.1:8000",
        "go build                 # static binary",
    ),
    dev=("go test ./...",),
    interface_line=(
        "interface: command-line (go run .) plus a web UI (go run . serve) — "
        "dependency-free net/http"
    ),
    gitignore="__PKG__\n__PKG__.exe\n*.test\n",
    ci=(
        "name: ci\n\non:\n  push:\n  pull_request:\n\njobs:\n  test:\n"
        "    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-go@v5\n"
        '        with: { go-version: "1.22" }\n'
        "      - name: Tests\n"
        "        run: go test ./...\n"
    ),
    docker=(
        "FROM golang:1.22-alpine AS build\n"
        "WORKDIR /app\n"
        "COPY . .\n"
        "RUN go build -o /bin/app .\n"
        "\n"
        "FROM alpine:3.20\n"
        "COPY --from=build /bin/app /bin/app\n"
        "ENV HOST=0.0.0.0\n"
        "EXPOSE 8000\n"
        'CMD ["/bin/app", "serve"]\n'
    ),
)
