"""Node.js stack: an ES-module project served with node:http, tested with node --test.

Dependency-free by design (no express, no node_modules) — the same "stdlib
first" idiom as detcode's own Python projects. The Python domain packs cannot
ride along on this stack; the skeleton marks exactly where the domain logic
goes, and the build decisions record that boundary.
"""
from __future__ import annotations

from . import Stack

_PACKAGE_JSON = '''{
  "name": "__PKG__",
  "version": "0.1.0",
  "description": "__PKG__ (generated by detcode)",
  "type": "module",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "test": "node --test"
  },
  "engines": { "node": ">=20" }
}
'''

_CORE = '''/**
 * Core logic for __PKG__.
 *
 * detcode generated this skeleton deterministically. The domain logic is
 * yours to specify: detcode's domain packs are Python-only, so on the Node.js
 * stack this function fails loudly instead of pretending to work.
 */
export function run(args) {
  throw new Error(
    "the domain logic for this project is not derivable from the direction alone; implement it in src/core.js"
  );
}
'''

_CLI = '''/** Command-line interface for __PKG__: node src/cli.js [inputs...] */
import { pathToFileURL } from "node:url";

import { run } from "./core.js";

export function main(argv) {
  if (argv.includes("--help")) {
    return { code: 0, output: "usage: node src/cli.js [inputs...]" };
  }
  try {
    return { code: 0, output: String(run(argv)) };
  } catch (err) {
    return { code: 1, output: `error: ${err.message}` };
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { code, output } = main(process.argv.slice(2));
  console.log(output);
  process.exit(code);
}
'''

_SERVER = '''/**
 * Minimal web UI for __PKG__ (generated by detcode, stack: node).
 *
 * Wraps the CLI in a dependency-free node:http server: a command typed in
 * the browser runs `main(argv)` in-process and returns its output.
 *
 *     node server.js [port]    ->  http://127.0.0.1:8000
 */
import { createServer } from "node:http";

import { main } from "./src/cli.js";

const PAGE = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>__PKG__</title>
<style>
  body { background: #181818; color: #ccc; font-family: ui-monospace, Consolas, monospace;
         max-width: 860px; margin: 40px auto; padding: 0 20px; font-size: 14px; }
  h1 { color: #fff; font-weight: 400; font-size: 20px; }
  .row { display: flex; gap: 8px; margin: 16px 0; }
  .tp { color: #89d185; align-self: center; }
  input { flex: 1; background: #252526; color: #ccc; border: 1px solid #3c3c3c;
          border-radius: 3px; padding: 8px 10px; font: inherit; }
  pre { background: #1e1e1e; border: 1px solid #3c3c3c; border-radius: 3px;
        padding: 12px; white-space: pre-wrap; min-height: 60px; }
  pre.err { color: #f48771; }
  .dim { color: #8a8a8a; font-size: 12.5px; }
</style></head><body>
<h1>__PKG__</h1>
<p class="dim">Commands run the project CLI (deterministic). Try: <code>--help</code></p>
<div class="row"><span class="tp">__PKG__&gt;</span>
<input id="cmd" autofocus placeholder="--help"></div>
<pre id="out"></pre>
<script>
const input = document.getElementById("cmd"), out = document.getElementById("out");
input.addEventListener("keydown", async e => {
  if (e.key !== "Enter") return;
  const res = await fetch("/api/run", { method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ command: input.value }) });
  const data = await res.json();
  out.textContent = data.output || "(no output)";
  out.className = data.ok ? "" : "err";
});
</script></body></html>
`;

function respond(res, status, type, body) {
  res.writeHead(status, { "Content-Type": type });
  res.end(body);
}

const server = createServer((req, res) => {
  if (req.method === "POST" && req.url === "/api/run") {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      let command = "";
      try {
        command = String(JSON.parse(body || "{}").command || "");
      } catch {
        respond(res, 400, "application/json",
          JSON.stringify({ ok: false, output: "body must be valid JSON" }));
        return;
      }
      const { code, output } = main(command.split(/\\s+/).filter(Boolean));
      respond(res, 200, "application/json",
        JSON.stringify({ ok: code === 0, exit: code, output }));
    });
    return;
  }
  if (req.method === "GET" && req.url === "/") {
    respond(res, 200, "text/html; charset=utf-8", PAGE);
    return;
  }
  respond(res, 404, "application/json", JSON.stringify({ ok: false, output: "not found" }));
});

const port = Number(process.argv[2]) || 8000;
server.listen(port, "127.0.0.1", () =>
  console.log(`__PKG__ web ui: http://127.0.0.1:${port}`)
);
'''

_TESTS = '''/** Tests for the generated __PKG__ skeleton: node --test */
import test from "node:test";
import assert from "node:assert/strict";

import { main } from "../src/cli.js";
import { run } from "../src/core.js";

test("cli --help is ok", () => {
  const { code, output } = main(["--help"]);
  assert.equal(code, 0);
  assert.match(output, /usage/);
});

test("core is explicit about missing logic", () => {
  // The skeleton must fail loudly, never pretend to work.
  assert.throws(() => run([]), /not derivable/);
});

test("cli surfaces core errors", () => {
  const { code, output } = main(["input.txt"]);
  assert.equal(code, 1);
  assert.match(output, /error:/);
});
'''


def _files() -> dict[str, str]:
    return {
        "package.json": _PACKAGE_JSON,
        "src/core.js": _CORE,
        "src/cli.js": _CLI,
        "server.js": _SERVER,
        "tests/core.test.js": _TESTS,
    }


STACK = Stack(
    key="node",
    title="Node.js",
    keywords=frozenset({"node", "nodejs", "express", "javascript", "js"}),
    description=(
        "a dependency-free Node.js (ES modules) project — node:http web UI, "
        "CLI, and node --test suite"
    ),
    language="javascript",
    dependencies=(),
    web_files=None,
    skeleton=_files,
    web_always=True,
    web_label="a node:http web UI",
    usage=(
        "node src/cli.js --help",
        "node server.js         # web UI at http://127.0.0.1:8000",
    ),
    dev=("node --test",),
)
