"""React stack: a Vite + React single-page app.

The same honest pattern as every other stack, moved client-side: the App is a
terminal-style UI over ``src/lib/core.js``, which fails loudly until the
domain logic is implemented. Core tests stay dependency-free (node --test);
the React toolchain (vite, @vitejs/plugin-react) arrives with npm install.
"""
from __future__ import annotations

from . import Stack

_PACKAGE_JSON = '''{
  "name": "__PKG__",
  "version": "0.1.0",
  "description": "__PKG__ (generated by detcode)",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "node --test"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.1",
    "vite": "^5.4.0"
  },
  "engines": { "node": ">=20" }
}
'''

_VITE_CONFIG = '''import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
});
'''

_INDEX_HTML = '''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>__PKG__</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
'''

_MAIN_JSX = '''import React from "react";
import { createRoot } from "react-dom/client";

import App from "./App.jsx";
import "./styles.css";

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
'''

_APP_JSX = '''/**
 * __PKG__ — a terminal-style UI over the core logic (generated by detcode).
 *
 * Commands run `run(args)` from src/lib/core.js client-side. The core is a
 * skeleton that fails loudly until the domain logic is implemented.
 */
import { useState } from "react";

import { run } from "./lib/core.js";

const USAGE = [
  "__PKG__ - generated by detcode (stack: react)",
  "",
  "usage: type a command and press Enter - it runs run(args) from",
  "src/lib/core.js, entirely client-side.",
  "",
  "  npm run dev      dev server at http://127.0.0.1:5173",
  "  npm run build    production bundle in dist/",
  "  node --test      run the core test suite",
  "",
  "The core is a skeleton that fails loudly until you implement it.",
].join("\\n");

export default function App() {
  const [command, setCommand] = useState("");
  const [output, setOutput] = useState("");
  const [failed, setFailed] = useState(false);

  const execute = () => {
    const args = command.split(/\\s+/).filter(Boolean);
    if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
      setOutput(USAGE);
      setFailed(false);
      return;
    }
    try {
      setOutput(String(run(args)));
      setFailed(false);
    } catch (err) {
      setOutput(`error: ${err.message}`);
      setFailed(true);
    }
  };

  return (
    <main>
      <h1>__PKG__</h1>
      <p className="dim">
        Commands run the core logic (deterministic). Try: <code>--help</code>
      </p>
      <div className="row">
        <span className="tp">__PKG__&gt;</span>
        <input
          autoFocus
          placeholder="--help"
          value={command}
          onChange={(e) => setCommand(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && execute()}
        />
      </div>
      <pre className={failed ? "err" : ""}>{output}</pre>
    </main>
  );
}
'''

_STYLES = '''body {
  background: #181818;
  color: #ccc;
  font-family: ui-monospace, Consolas, monospace;
  max-width: 860px;
  margin: 40px auto;
  padding: 0 20px;
  font-size: 14px;
}
h1 { color: #fff; font-weight: 400; font-size: 20px; }
.row { display: flex; gap: 8px; margin: 16px 0; }
.tp { color: #89d185; align-self: center; }
input {
  flex: 1;
  background: #252526;
  color: #ccc;
  border: 1px solid #3c3c3c;
  border-radius: 3px;
  padding: 8px 10px;
  font: inherit;
}
pre {
  background: #1e1e1e;
  border: 1px solid #3c3c3c;
  border-radius: 3px;
  padding: 12px;
  white-space: pre-wrap;
  min-height: 60px;
}
pre.err { color: #f48771; }
.dim { color: #8a8a8a; font-size: 12.5px; }
'''

_CORE = '''/**
 * Core logic for __PKG__.
 *
 * detcode generated this skeleton deterministically. The domain logic is
 * yours to specify: detcode's domain packs are Python-only, so on the React
 * stack this function fails loudly instead of pretending to work. Keep it
 * framework-free — the tests run it under node --test with no build step.
 */
export function run(args) {
  throw new Error(
    "the domain logic for this project is not derivable from the direction alone; implement it in src/lib/core.js"
  );
}
'''

_TESTS = '''/** Tests for the generated __PKG__ core: node --test (no build step needed) */
import test from "node:test";
import assert from "node:assert/strict";

import { run } from "../src/lib/core.js";

test("core is explicit about missing logic", () => {
  // The skeleton must fail loudly, never pretend to work.
  assert.throws(() => run([]), /not derivable/);
});
'''


def _files() -> dict[str, str]:
    return {
        "package.json": _PACKAGE_JSON,
        "vite.config.js": _VITE_CONFIG,
        "index.html": _INDEX_HTML,
        "src/main.jsx": _MAIN_JSX,
        "src/App.jsx": _APP_JSX,
        "src/styles.css": _STYLES,
        "src/lib/core.js": _CORE,
        "tests/core.test.js": _TESTS,
    }


STACK = Stack(
    key="react",
    title="React (Vite)",
    keywords=frozenset({"react", "reactjs", "vite", "spa"}),
    description=(
        "a Vite + React single-page app — the domain logic lives client-side "
        "in src/lib/core.js; adds dependencies: react, react-dom, vite"
    ),
    language="javascript",
    skeleton=_files,
    web_always=True,
    web_label="a React SPA",
    usage=(
        "npm install",
        "npm run dev            # dev server at http://127.0.0.1:5173",
        "npm run build          # production bundle in dist/",
    ),
    dev=("node --test",),
    interface_line=(
        "interface: single-page React app (npm run dev) — the domain logic "
        "lives client-side in src/lib/core.js"
    ),
    gitignore="node_modules/\ndist/\n*.log\n",
    ci=(
        "name: ci\n\non:\n  push:\n  pull_request:\n\njobs:\n  test:\n"
        "    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-node@v4\n"
        '        with: { node-version: "22" }\n'
        "      - name: Tests\n"
        "        run: node --test\n"
        "      - name: Install\n"
        "        run: npm install\n"
        "      - name: Build\n"
        "        run: npm run build\n"
    ),
    docker=(
        "FROM node:22-slim AS build\n"
        "WORKDIR /app\n"
        "COPY . .\n"
        "RUN npm install && npm run build\n"
        "\n"
        "FROM nginx:alpine\n"
        "COPY --from=build /app/dist /usr/share/nginx/html\n"
        "EXPOSE 80\n"
    ),
)
