"""Rust stack: a Cargo binary + library crate with unit and integration tests.

CLI-first: Rust's standard library ships no HTTP server, so this stack is
honest about it — the interface decision says to add axum or actix-web when a
web UI is needed. The core fails loudly until the domain logic exists.
"""
from __future__ import annotations

from . import Stack

_CARGO_TOML = '''[package]
name = "__PKG__"
version = "0.1.0"
edition = "2021"
description = "__PKG__ (generated by detcode)"

[dependencies]
'''

_LIB = '''//! Core logic for __PKG__.
//!
//! detcode generated this skeleton deterministically. The domain logic is
//! yours to specify: detcode's domain packs are Python-only, so on the Rust
//! stack this function fails loudly instead of pretending to work.

/// Entry point for the __PKG__ pipeline.
pub fn run(_args: &[String]) -> Result<String, String> {
    Err(String::from(
        "the domain logic for this project is not derivable from the direction alone; implement it in src/lib.rs",
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    // The skeleton must fail loudly, never pretend to work.
    #[test]
    fn core_is_explicit_about_missing_logic() {
        let err = run(&[]).unwrap_err();
        assert!(err.contains("not derivable"));
    }
}
'''

_MAIN = '''//! Command-line interface for __PKG__: cargo run -- [inputs...]
use std::env;
use std::process;

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    if args.iter().any(|a| a == "--help") {
        println!("usage: __PKG__ [inputs...]");
        return;
    }
    match __PKG__::run(&args) {
        Ok(output) => println!("{output}"),
        Err(err) => {
            eprintln!("error: {err}");
            process::exit(1);
        }
    }
}
'''

_INTEGRATION = '''//! Integration test: the public API stays honest about missing logic.
use __PKG__::run;

#[test]
fn core_fails_loudly_from_the_outside() {
    let err = run(&[String::from("input.txt")]).unwrap_err();
    assert!(err.contains("not derivable"));
}
'''


def _files() -> dict[str, str]:
    return {
        "Cargo.toml": _CARGO_TOML,
        "src/lib.rs": _LIB,
        "src/main.rs": _MAIN,
        "tests/integration.rs": _INTEGRATION,
    }


STACK = Stack(
    key="rust",
    title="Rust",
    keywords=frozenset({"rust", "cargo"}),
    description=(
        "a Cargo binary + library crate with unit and integration tests — "
        "CLI-first, dependency-free"
    ),
    language="rust",
    skeleton=_files,
    web_always=False,
    usage=(
        "cargo run -- --help",
        "cargo build --release    # binary in target/release/",
    ),
    dev=("cargo test",),
    interface_line=(
        "interface: command-line (cargo run) — Rust std ships no HTTP server; "
        "add axum or actix-web when you need one"
    ),
    gitignore="target/\n",
    ci=(
        "name: ci\n\non:\n  push:\n  pull_request:\n\njobs:\n  test:\n"
        "    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - name: Tests\n"
        "        run: cargo test\n"
    ),
)
