"""TypeScript stack: a strict, dependency-free Node.js project compiled with tsc.

Same shape as the node stack — node:http web UI, CLI, node --test suite —
but written in strict TypeScript (NodeNext modules). Tests compile with the
project and run against dist/, so what is tested is what ships.
"""
from __future__ import annotations

from . import Stack

_PACKAGE_JSON = '''{
  "name": "__PKG__",
  "version": "0.1.0",
  "description": "__PKG__ (generated by detcode)",
  "type": "module",
  "main": "dist/server.js",
  "scripts": {
    "build": "tsc",
    "start": "npm run build && node dist/server.js",
    "cli": "npm run build && node dist/cli.js",
    "test": "npm run build && node --test \\"dist/tests/*.test.js\\""
  },
  "devDependencies": {
    "@types/node": "^22.5.0",
    "typescript": "^5.5.4"
  },
  "engines": { "node": ">=20" }
}
'''

_TSCONFIG = '''{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "declaration": true,
    "sourceMap": true
  },
  "include": ["src"]
}
'''

_CORE = '''/**
 * Core logic for __PKG__.
 *
 * detcode generated this skeleton deterministically. The domain logic is
 * yours to specify: detcode's domain packs are Python-only, so on the
 * TypeScript stack this function fails loudly instead of pretending to work.
 */
export function run(args: string[]): string {
  throw new Error(
    "the domain logic for this project is not derivable from the direction alone; implement it in src/core.ts"
  );
}
'''

_CLI = '''/** Command-line interface for __PKG__: node dist/cli.js [inputs...] */
import { pathToFileURL } from "node:url";

import { run } from "./core.js";

export interface CliResult {
  code: number;
  output: string;
}

const USAGE = [
  "__PKG__ - generated by detcode (stack: typescript)",
  "",
  "usage:",
  "  npm run cli -- [inputs...]    run the core pipeline",
  "  npm start                     web UI at http://127.0.0.1:8000",
  "  npm test                      build and run the test suite",
  "",
  "The domain logic lives in src/core.ts - a skeleton that fails loudly",
  "until you implement it.",
].join("\\n");

export function main(argv: string[]): CliResult {
  if (argv.length === 0 || argv.includes("--help") || argv.includes("-h")) {
    return { code: 0, output: USAGE };
  }
  try {
    return { code: 0, output: String(run(argv)) };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { code: 1, output: `error: ${message}` };
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { code, output } = main(process.argv.slice(2));
  console.log(output);
  process.exit(code);
}
'''

_SERVER = '''/**
 * Minimal web UI for __PKG__ (generated by detcode, stack: typescript).
 *
 * Wraps the CLI in a dependency-free node:http server: a command typed in
 * the browser runs `main(argv)` in-process and returns its output.
 *
 *     npm start [-- port]    ->  http://127.0.0.1:8000
 */
import { createServer, IncomingMessage, ServerResponse } from "node:http";

import { main } from "./cli.js";

const PAGE = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>__PKG__</title>
<style>
  body { background: #181818; color: #ccc; font-family: ui-monospace, Consolas, monospace;
         max-width: 860px; margin: 40px auto; padding: 0 20px; font-size: 14px; }
  h1 { color: #fff; font-weight: 400; font-size: 20px; }
  .row { display: flex; gap: 8px; margin: 16px 0; }
  .tp { color: #89d185; align-self: center; }
  input { flex: 1; background: #252526; color: #ccc; border: 1px solid #3c3c3c;
          border-radius: 3px; padding: 8px 10px; font: inherit; }
  pre { background: #1e1e1e; border: 1px solid #3c3c3c; border-radius: 3px;
        padding: 12px; white-space: pre-wrap; min-height: 60px; }
  pre.err { color: #f48771; }
  .dim { color: #8a8a8a; font-size: 12.5px; }
</style></head><body>
<h1>__PKG__</h1>
<p class="dim">Commands run the project CLI (deterministic). Try: <code>--help</code></p>
<div class="row"><span class="tp">__PKG__&gt;</span>
<input id="cmd" autofocus placeholder="--help"></div>
<pre id="out"></pre>
<script>
const input = document.getElementById("cmd"), out = document.getElementById("out");
input.addEventListener("keydown", async e => {
  if (e.key !== "Enter") return;
  const res = await fetch("/api/run", { method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ command: input.value }) });
  const data = await res.json();
  out.textContent = data.output || "(no output)";
  out.className = data.ok ? "" : "err";
});
</script></body></html>
`;

function respond(res: ServerResponse, status: number, type: string, body: string): void {
  res.writeHead(status, { "Content-Type": type });
  res.end(body);
}

const server = createServer((req: IncomingMessage, res: ServerResponse) => {
  if (req.method === "POST" && req.url === "/api/run") {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      let command = "";
      try {
        command = String(JSON.parse(body || "{}").command || "");
      } catch {
        respond(res, 400, "application/json",
          JSON.stringify({ ok: false, output: "body must be valid JSON" }));
        return;
      }
      const { code, output } = main(command.split(/\\s+/).filter(Boolean));
      respond(res, 200, "application/json",
        JSON.stringify({ ok: code === 0, exit: code, output }));
    });
    return;
  }
  if (req.method === "GET" && req.url === "/") {
    respond(res, 200, "text/html; charset=utf-8", PAGE);
    return;
  }
  respond(res, 404, "application/json", JSON.stringify({ ok: false, output: "not found" }));
});

const port = Number(process.argv[2]) || 8000;
const host = process.env.HOST || "127.0.0.1";
server.listen(port, host, () =>
  console.log(`__PKG__ web ui: http://${host}:${port}`)
);
'''

_TESTS = '''/** Tests for the generated __PKG__ skeleton: npm test */
import test from "node:test";
import assert from "node:assert/strict";

import { main } from "../cli.js";
import { run } from "../core.js";

test("cli --help is ok", () => {
  const { code, output } = main(["--help"]);
  assert.equal(code, 0);
  assert.match(output, /usage/);
});

test("core is explicit about missing logic", () => {
  // The skeleton must fail loudly, never pretend to work.
  assert.throws(() => run([]), /not derivable/);
});

test("cli surfaces core errors", () => {
  const { code, output } = main(["input.txt"]);
  assert.equal(code, 1);
  assert.match(output, /error:/);
});
'''


def _files() -> dict[str, str]:
    return {
        "package.json": _PACKAGE_JSON,
        "tsconfig.json": _TSCONFIG,
        "src/core.ts": _CORE,
        "src/cli.ts": _CLI,
        "src/server.ts": _SERVER,
        "src/tests/core.test.ts": _TESTS,
    }


STACK = Stack(
    key="typescript",
    title="TypeScript",
    keywords=frozenset({"typescript", "ts"}),
    description=(
        "a strict TypeScript (NodeNext) project compiled with tsc — node:http "
        "web UI, CLI, and node --test suite against dist/"
    ),
    language="typescript",
    skeleton=_files,
    web_always=True,
    web_label="a node:http web UI",
    usage=(
        "npm install",
        "npm run cli -- --help",
        "npm start              # web UI at http://127.0.0.1:8000",
    ),
    dev=("npm install", "npm test"),
    interface_line=(
        "interface: command-line (node dist/cli.js) plus a web UI "
        "(node dist/server.js) — strict TypeScript compiled with tsc, "
        "dependency-free node:http"
    ),
    gitignore="node_modules/\ndist/\n*.log\n",
    ci=(
        "name: ci\n\non:\n  push:\n  pull_request:\n\njobs:\n  test:\n"
        "    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-node@v4\n"
        '        with: { node-version: "22" }\n'
        "      - name: Install\n"
        "        run: npm install\n"
        "      - name: Tests\n"
        "        run: npm test\n"
    ),
    docker=(
        "FROM node:22-slim\n"
        "WORKDIR /app\n"
        "COPY . .\n"
        "RUN npm install && npm run build\n"
        "ENV HOST=0.0.0.0\n"
        "EXPOSE 8000\n"
        'CMD ["node", "dist/server.js"]\n'
    ),
)
